language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t dev1000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dev1000/docker-react npm run test